version: '3.3'
services:
   db:
     image: mysql:8.0
     container_name: docker_mysql_8.0
     volumes:
       - ./db_vol8:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: Mysqldb.2021
       MYSQL_DATABASE: solucion
       MYSQL_USER: admin
       MYSQL_PASSWORD: V4lurq123!
     ports:
       - 3306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Mysqldb.2021
   tomcat:
    build:
      context: .       
    depends_on:
      - db
    image: fabric8/tomcat-7
    container_name: tomcat_7
    volumes:
      - ./tomcat/birt2:/usr/local/tomcat/webapps/birt2
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: Mysqldb.2021
      MYSQL_DATABASE: solucion
      MYSQL_USER: admin
      MYSQL_PASSWORD: V4lurq123!
   httpd:
    container_name: apache-php
    image: romeoz/docker-apache-php:5.6
    ports:
        - "80:80"
    volumes:
        - ./php/www/app:/var/www/app
    depends_on:
      - db
volumes:
    db_vol:      